// ============================================================
// SEED PSIKOTEST — 6 kategori, berurutan seperti tes asli
// Kategori: verbal, numerik, logika, spasial, matematika, kepribadian
// Level: mudah -> sedang -> sulit
// ============================================================

const categories = [
  { tipe: 'psikotest', kode: 'verbal', nama: 'Tes Verbal', deskripsi: 'Sinonim, antonim, dan analogi kata untuk mengukur kemampuan berbahasa dan pemahaman kosakata.', urutan: 1 },
  { tipe: 'psikotest', kode: 'numerik', nama: 'Tes Numerik', deskripsi: 'Deret angka dan kemampuan hitung cepat yang mengukur ketajaman berpikir angka.', urutan: 2 },
  { tipe: 'psikotest', kode: 'logika', nama: 'Tes Logika', deskripsi: 'Penalaran logis, silogisme, dan kesimpulan untuk mengukur daya nalar.', urutan: 3 },
  { tipe: 'psikotest', kode: 'spasial', nama: 'Tes Spasial & Figural', deskripsi: 'Rotasi, pencerminan, dan pola gambar untuk mengukur kemampuan visual-spasial (dalam bentuk diagram).', urutan: 4 },
  { tipe: 'psikotest', kode: 'matematika', nama: 'Tes Matematika Dasar', deskripsi: 'Pecahan, persen, rasio, kecepatan, untung-rugi: materi dasar yang sering muncul saat tes.', urutan: 5 },
  { tipe: 'psikotest', kode: 'kepribadian', nama: 'Tes Kepribadian', deskripsi: 'Pilihan sikap dalam situasi kerja untuk melihat karakter (tidak ada jawaban salah mutlak).', urutan: 6 }
];

const q = (kode, level, urutan, pertanyaan, diagram, opsi, kunci, pembahasan) =>
  ({ kode, level, nomor_urutan: urutan, pertanyaan, diagram, opsi, kunci, pembahasan });

const questions = [
  // ============ TES VERBAL ============
  q('verbal', 'mudah', 1, 'Sinonim kata "mendapatkan" adalah...', null,
    ['memperoleh', 'menyerahkan', 'membuang', 'mengabaikan', 'menyimpan'],
    1, 'Memperoleh = mendapatkan. Pilihan lain justru kebalikan atau tidak sepadan.'),
  q('verbal', 'mudah', 2, 'Antonim (lawan kata) dari "terang" adalah...', null,
    ['gelap', 'cerah', 'jelas', 'bersinar', 'putih'],
    1, 'Lawan kata terang adalah gelap.'),
  q('verbal', 'mudah', 3, 'Lengkapilah analogi: "Burung : Terbang = Ikan : ..."', null,
    ['Berenang', 'Berjalan', 'Terbang', 'Merayap', 'Melompat'],
    1, 'Burung bergerak dengan cara terbang, ikan bergerak dengan cara berenang.'),
  q('verbal', 'mudah', 4, 'Sinonim kata "abadi" adalah...', null,
    ['kekal', 'sementara', 'fana', 'sesaat', 'singkat'],
    1, 'Abadi = kekal, tidak berkesudahan.'),
  q('verbal', 'sedang', 5, 'Antonim kata "optimis" adalah...', null,
    ['pesimis', 'semangat', 'yakin', 'berharap', 'gigih'],
    1, 'Optimis = berpandangan baik/semangat; lawannya pesimis (berpandangan buruk).'),
  q('verbal', 'sedang', 6, 'Lengkapilah analogi: "Pedagang : Toko = Dokter : ..."', null,
    ['Rumah sakit', 'Pasar', 'Apotek', 'Laboratorium', 'Sekolah'],
    1, 'Tempat kerja pedagang adalah toko; tempat kerja dokter adalah rumah sakit.'),
  q('verbal', 'sedang', 7, 'Sinonim kata "kontemporer" adalah...', null,
    ['modern', 'kuno', 'tradisional', 'klasik', 'lampau'],
    1, 'Kontemporer = masa kini / modern.'),
  q('verbal', 'sedang', 8, 'Antonim kata "mayoritas" adalah...', null,
    ['minoritas', 'keseluruhan', 'dominan', 'sebagian besar', 'umum'],
    1, 'Mayoritas = bagian terbesar; lawannya minoritas.'),
  q('verbal', 'sulit', 9, 'Lengkapilah analogi: "Pohon : Hutan = Bintang : ..."', null,
    ['Galaksi', 'Planet', 'Matahari', 'Satelit', 'Komet'],
    1, 'Kumpulan pohon membentuk hutan; kumpulan bintang membentuk galaksi.'),
  q('verbal', 'sulit', 10, 'Sinonim kata "paradoks" adalah...', null,
    ['pertentangan', 'kesamaan', 'persetujuan', 'keselarasan', 'kejelasan'],
    1, 'Paradoks = pernyataan yang seolah bertentangan / bertentangan dengan akal sehat.'),
  q('verbal', 'sulit', 11, 'Antonim kata "eksternal" adalah...', null,
    ['internal', 'luar', 'tambahan', 'lengkap', 'tidak langsung'],
    1, 'Eksternal = dari luar; lawannya internal (dari dalam).'),
  q('verbal', 'sulit', 12, 'Lengkapilah analogi: "Demokrasi : Rakyat = Otokrasi : ..."', null,
    ['Penguasa', 'Parlemen', 'Hukum', 'Konstitusi', 'Hakim'],
    1, 'Dalam demokrasi kekuasaan di tangan rakyat; dalam otokrasi kekuasaan di tangan penguasa tunggal.'),

  // ============ TES NUMERIK ============
  q('numerik', 'mudah', 1, 'Lanjutkan deret: 2, 4, 6, 8, ...', null,
    ['10', '11', '12', '9', '14'],
    1, 'Pola: tambah 2 setiap langkah, sehingga 8 + 2 = 10.'),
  q('numerik', 'mudah', 2, 'Lanjutkan deret: 3, 6, 12, 24, ...', null,
    ['48', '36', '42', '30', '54'],
    1, 'Pola: dikali 2, sehingga 24 × 2 = 48.'),
  q('numerik', 'mudah', 3, 'Hitung: 5 + 7 × 2 = ...', null,
    ['19', '24', '26', '17', '14'],
    1, 'Kerjakan perkalian dulu: 7 × 2 = 14, lalu 5 + 14 = 19.'),
  q('numerik', 'mudah', 4, 'Hitung: 1/2 + 1/4 = ...', null,
    ['3/4', '2/3', '1/5', '1/3', '1'],
    1, 'Samakan penyebut: 2/4 + 1/4 = 3/4.'),
  q('numerik', 'sedang', 5, 'Lanjutkan deret: 1, 1, 2, 3, 5, 8, ...', null,
    ['13', '11', '12', '14', '10'],
    1, 'Pola Fibonacci: bilangan berikutnya = jumlah dua bilangan sebelumnya (5 + 8 = 13).'),
  q('numerik', 'sedang', 6, 'Lanjutkan deret: 100, 95, 85, 70, 50, ...', null,
    ['25', '30', '35', '20', '40'],
    1, 'Pola: dikurangi 5, 10, 15, 20, 25 → 50 - 25 = 25.'),
  q('numerik', 'sedang', 7, 'Berapakah 25% dari 240?', null,
    ['60', '75', '48', '80', '50'],
    1, '25% = 1/4 → 240 : 4 = 60.'),
  q('numerik', 'sedang', 8, 'Bilangan ganjil ke-9 adalah...', null,
    ['17', '15', '19', '21', '13'],
    1, 'Deret ganjil: 1,3,5,7,9,11,13,15,17 → yang ke-9 = 17.'),
  q('numerik', 'sulit', 9, 'Lanjutkan deret: 2, 3, 5, 8, 12, 17, ...', null,
    ['23', '22', '21', '24', '20'],
    1, 'Pola: +1, +2, +3, +4, +5, +6 → 17 + 6 = 23.'),
  q('numerik', 'sulit', 10, 'Rata-rata dari bilangan 8, 12, 16, 20, 24 adalah...', null,
    ['16', '18', '15', '17', '14'],
    1, 'Jumlah = 80, banyak data = 5, rata-rata = 80 : 5 = 16.'),
  q('numerik', 'sulit', 11, 'Harga sebuah barang naik 20% lalu turun 10%. Harga akhir barang tersebut adalah... (dibanding harga awal)', null,
    ['naik 8%', 'turun 8%', 'tetap', 'naik 10%', 'turun 10%'],
    1, 'Misal awal 100 → naik 20% = 120 → turun 10% dari 120 = 12 → 108. Berarti naik 8%.'),
  q('numerik', 'sulit', 12, 'Jika x + 2y = 10 dan x - y = 4, maka nilai y adalah...', null,
    ['2', '3', '4', '5', '6'],
    1, 'Kurangkan: (x+2y)-(x-y)=10-4 → 3y=6 → y=2.'),

  // ============ TES LOGIKA ============
  q('logika', 'mudah', 1, 'Semua kucing suka ikan. Miko adalah seekor kucing. Kesimpulan yang benar adalah...', null,
    ['Miko suka ikan', 'Miko tidak suka ikan', 'Semua yang suka ikan adalah kucing', 'Miko bukan kucing', 'Tidak dapat disimpulkan'],
    1, 'Dari "semua kucing suka ikan" dan "Miko kucing", maka pasti Miko suka ikan (silogisme).'),
  q('logika', 'mudah', 2, 'Jika hujan, maka jalan basah. Ternyata jalan tidak basah. Kesimpulan yang benar adalah...', null,
    ['Tidak hujan', 'Pasti hujan', 'Hujan tapi jalan kering', 'Tidak dapat disimpulkan', 'Ada angin kencang'],
    1, 'Modus tollens: jika p→q dan q salah, maka p salah. Tidak hujan.'),
  q('logika', 'mudah', 3, 'A lebih tinggi daripada B, dan B lebih tinggi daripada C. Siapa yang paling tinggi?', null,
    ['A', 'B', 'C', 'A dan B sama tinggi', 'Tidak dapat disimpulkan'],
    1, 'Karena A > B dan B > C, maka A paling tinggi.'),
  q('logika', 'mudah', 4, 'Semua karyawan rajin. Andi tidak rajin. Kesimpulan yang benar adalah...', null,
    ['Andi bukan karyawan', 'Andi adalah karyawan', 'Andi karyawan yang rajin', 'Andi malas tapi karyawan', 'Tidak dapat disimpulkan'],
    1, 'Jika semua karyawan rajin, maka yang tidak rajin bukanlah karyawan.'),
  q('logika', 'sedang', 5, 'Semua burung bertelur. Sebagian burung adalah hewan peliharaan. Kesimpulan yang paling sahih adalah...', null,
    ['Sebagian hewan peliharaan adalah burung yang bertelur', 'Semua hewan peliharaan bertelur', 'Semua burung adalah hewan peliharaan', 'Tidak ada hewan peliharaan yang bertelur', 'Semua hewan peliharaan adalah burung'],
    1, 'Karena sebagian burung adalah hewan peliharaan dan semua burung bertelur, maka sebagian hewan peliharaan (yang burung) bertelur.'),
  q('logika', 'sedang', 6, 'Di rak buku: buku A terletak di kiri B, buku C di kanan B, dan D berada paling kiri. Urutan buku dari kiri ke kanan adalah...', null,
    ['D, A, B, C', 'A, D, B, C', 'D, B, A, C', 'C, B, A, D', 'A, B, C, D'],
    1, 'D paling kiri; A di kiri B; C di kanan B. Maka: D, A, B, C.'),
  q('logika', 'sedang', 7, 'Jika harga BBM naik, maka harga angkutan umum naik. Ternyata harga angkutan umum naik. Apakah bisa disimpulkan harga BBM pasti naik?', null,
    ['Belum tentu, sebab bisa ada faktor lain', 'Pasti BBM naik', 'Pasti BBM tidak naik', 'Tidak ada hubungan', 'BBM naik setelah angkutan naik'],
    1, 'Ini kesalahan logika "mengafirmasi konsekuen" — kenaikan angkutan bisa disebabkan faktor lain.'),
  q('logika', 'sedang', 8, 'Budi lebih tua dari Dewi. Cici lebih muda dari Dewi dan lebih tua dari Budi. Siapa yang paling muda?', null,
    ['Dewi', 'Budi', 'Cici', 'Budi dan Cici sama', 'Tidak dapat disimpulkan'],
    1, 'Urutan umur: Cici > Budi > Dewi (sebab Cici lebih muda dari Dewi tapi lebih tua dari Budi → berarti Cici < Dewi). Perhatikan: "Cici lebih muda dari Dewi" dan "Cici lebih tua dari Budi" → Budi < Cici < Dewi. Jadi Dewi paling muda.'),
  q('logika', 'sulit', 9, 'Semua pensiunan adalah warga senior. Sebagian warga senior adalah pengurus RT. Kesimpulan yang TIDAK sahih adalah...', null,
    ['Sebagian pengurus RT adalah pensiunan', 'Sebagian warga senior bukan pensiunan', 'Semua pensiunan warga senior', 'Ada warga senior yang menjadi pengurus RT', 'Sebagian pensiunan adalah warga senior'],
    1, 'Dari premis tersebut, tidak dapat dipastikan pengurus RT itu pensiunan — boleh jadi warga senior yang bukan pensiunan.'),
  q('logika', 'sulit', 10, 'Jika A=1, B=2, C=3, ... , maka jumlah nilai huruf dari kata "PADU" adalah...', null,
    ['42', '40', '36', '38', '44'],
    1, 'P=16, A=1, D=4, U=21 → 16+1+4+21 = 42.'),
  q('logika', 'sulit', 11, 'Dalam lomba balap: W finish sebelum X, Y finish sebelum W, dan Z finish setelah Y. Jika hanya ada 4 pembalap, urutan finis ke-1 sampai ke-4 adalah...', null,
    ['Y, W, X, Z', 'W, X, Y, Z', 'Y, W, Z, X', 'W, Y, Z, X', 'Z, Y, W, X'],
    1, 'Y < W, W < X, dan Z setelah Y → kemungkinan: Y, W, X, Z (Z harus setelah Y dan posisi tersisa paling akhir).'),
  q('logika', 'sulit', 12, 'Semua A adalah B. Semua B adalah C. Tidak ada C yang merupakan D. Kesimpulan yang benar adalah...', null,
    ['Tidak ada A yang merupakan D', 'Semua C adalah A', 'Sebagian A adalah D', 'Semua D adalah A', 'Tidak dapat disimpulkan'],
    1, 'Karena semua A ⊂ B ⊂ C dan C tidak beririsan dengan D, maka A pasti tidak beririsan dengan D.'),

  // ============ TES SPASIAL & FIGURAL ============
  q('spasial', 'mudah', 1, 'Perhatikan pola perpindahan titik hitam berikut. Pola selanjutnya (nomor 4) adalah...', `
Pola 1:   Pola 2:   Pola 3:
. . .     . . .     . . .
. . .     . . .     . . .
. . .     . . .     . . .
(titik   (titik    (titik
 berpindah dari
 pojok kiri atas
 turun diagonal)
`,
    ['Titik berpindah ke pojok kanan bawah', 'Titik kembali ke pojok kiri atas', 'Titik di tengah', 'Titik di pojok kiri bawah', 'Titik di pojok kanan atas'],
    1, 'Pola 1→2→3 titik bergerak diagonal satu langkah ke kanan bawah; langkah ke-4 sampai di pojok kanan bawah.'),
  q('spasial', 'mudah', 2, 'Sebuah persegi dibagi menjadi 4 bagian sama besar. Berapa jumlah seluruh persegi (termasuk yang besar) pada gambar tersebut?', `
+---+---+
|   |   |
+---+---+
|   |   |
+---+---+
`,
    ['5', '4', '3', '6', '7'],
    1, 'Ada 4 persegi kecil + 1 persegi besar = 5 persegi.'),
  q('spasial', 'mudah', 3, 'Manakah bangun yang memiliki sumbu simetri vertikal (terbelah kiri-kanan sama)?', null,
    ['Segitiga sama kaki', 'Huruf "F"', 'Zigzag tidak beraturan', 'Bentuk panah miring', 'Tidak ada yang benar'],
    1, 'Segitiga sama kaki dapat dibagi menjadi dua bagian yang identik oleh sumbu vertikal.'),
  q('spasial', 'mudah', 4, 'Huruf "L" berikut diputar 90 derajat searah jarum jam. Bentuk hasil putarannya adalah...', `
Bentuk awal:
.
.
.
. . .
`,
    ['Berbentuk L terbalik menghadap kanan-bawah (berputar)', 'Tetap sama seperti awal', 'Menjadi garis lurus', 'Menjadi huruf "T"', 'Menjadi huruf "V"'],
    1, 'Memutar bentuk L sebesar 90 derajat akan mengubah arah "kakinya" menjadi menghadap kanan-bawah.'),
  q('spasial', 'sedang', 5, 'Hitung jumlah segitiga pada gambar piramida berikut:', `
   /\\
  /__\\
 /\\  /\\
/__\\/__\\
`,
    ['5', '3', '4', '6', '7'],
    1, 'Ada 4 segitiga kecil + 1 segitiga besar = 5 segitiga.'),
  q('spasial', 'sedang', 6, 'Sebuah lingkaran kecil berputar searah jarum jam mengelilingi sudut-sudut persegi (posisi 1: kiri-atas, posisi 2: kanan-atas, posisi 3: kanan-bawah). Posisi ke-4 adalah...', `
Posisi 1    Posisi 2    Posisi 3
o-----      ----o       ----
|    |      |    |      |    |
|    |      |    |      |    |
-----       -----       ----o
`,
    ['Kiri-bawah', 'Kiri-atas', 'Tengah', 'Kanan-atas', 'Kiri-tengah'],
    1, 'Urutan searah jarum jam: kiri-atas → kanan-atas → kanan-bawah → kiri-bawah.'),
  q('spasial', 'sedang', 7, 'Huruf "b" jika dicerminkan terhadap garis mendatar (horizontal) akan menjadi...', null,
    ['p', 'd', 'q', 'b', '6'],
    1, 'Huruf b dicerminkan horizontal menjadi p (lengkungan tetap di sisi yang sama secara horizontal).'),
  q('spasial', 'sedang', 8, 'Manakah di antara berikut yang BUKAN merupakan hasil pencerminan cermin dari angka 6?', null,
    ['6', 'g', 'seperti angka 6 terbalik', 'bentuk cermin cermin', 'tidak ada'],
    1, 'Pencerminan angka 6 akan terlihat seperti "e" atau "g" tergantung cerminnya; angka 6 yang utuh bukan hasil cermin.'),
  q('spasial', 'sulit', 9, 'Deret berikut menunjukkan banyak titik: 1, 3, 5, ... Banyak titik pada pola ke-5 adalah...', null,
    ['9', '7', '11', '10', '8'],
    1, 'Pola ganjil: 1,3,5,7,9 → pola ke-5 = 9.'),
  q('spasial', 'sulit', 10, 'Huruf "F" diputar 90 derajat berlawanan arah jarum jam. Bentuk hasilnya paling mirip dengan...', null,
    ['huruf F yang miring ke kiri (kaki atas jadi bawah)', 'huruf F biasa', 'huruf E', 'huruf T', 'garis lurus'],
    1, 'Memutar F berlawanan arah jarum jam membuat bagian atas (garis pendek) berpindah ke kiri-bawah.'),
  q('spasial', 'sulit', 11, 'Perhatikan urutan gambar berikut. Gambar yang berbeda (tidak sesuai pola) adalah...', null,
    ['Gambar ketiga yang bentuknya terbalik dari pola', 'Gambar pertama', 'Gambar kedua', 'Gambar keempat', 'Semua sama'],
    1, 'Pada deret yang polanya konsisten, satu gambar dengan orientasi terbalik dianggap ganjil.'),
  q('spasial', 'sulit', 12, 'Berapa banyak kubus paling sedikit untuk menyusun bentuk berikut ini? (susunan: 1 di lapis atas, 4 di lapis bawah)', `
  X
XXXX
`,
    ['5', '4', '6', '7', '8'],
    1, 'Lapis bawah 4 kubus + 1 kubus di atas = 5 kubus.'),

  // ============ TES MATEMATIKA DASAR ============
  q('matematika', 'mudah', 1, 'Berapakah 3/5 dari 100?', null,
    ['60', '50', '40', '75', '80'],
    1, '3/5 × 100 = 300/5 = 60.'),
  q('matematika', 'mudah', 2, 'Berapakah 15% dari 200?', null,
    ['30', '25', '20', '35', '15'],
    1, '15/100 × 200 = 30.'),
  q('matematika', 'mudah', 3, 'Harga sebuah tas Rp50.000 mendapat diskon 10%. Berapa yang harus dibayar?', null,
    ['Rp45.000', 'Rp40.000', 'Rp47.500', 'Rp42.500', 'Rp50.000'],
    1, 'Diskon = 10% × 50.000 = 5.000 → bayar 50.000 - 5.000 = 45.000.'),
  q('matematika', 'mudah', 4, 'Hitung: 120 + 45 - 60 = ...', null,
    ['105', '115', '95', '125', '85'],
    1, '120 + 45 = 165; 165 - 60 = 105.'),
  q('matematika', 'sedang', 5, 'Dua bilangan memiliki perbandingan 3 : 5 dan jumlah keduanya 80. Bilangan terkecil adalah...', null,
    ['30', '50', '40', '20', '35'],
    1, 'Jumlah bagian = 8. Satu bagian = 80/8 = 10. Bilangan terkecil = 3 × 10 = 30.'),
  q('matematika', 'sedang', 6, 'Sebuah mobil melaju 60 km/jam dan menempuh jarak 150 km. Berapa waktu yang dibutuhkan?', null,
    ['2,5 jam', '2 jam', '3 jam', '1,5 jam', '4 jam'],
    1, 'Waktu = jarak / kecepatan = 150 / 60 = 2,5 jam.'),
  q('matematika', 'sedang', 7, 'Andi membeli barang seharga Rp80.000 lalu menjualnya dengan untung 20%. Harga jualnya adalah...', null,
    ['Rp96.000', 'Rp100.000', 'Rp90.000', 'Rp86.000', 'Rp104.000'],
    1, 'Untung = 20% × 80.000 = 16.000 → harga jual = 96.000.'),
  q('matematika', 'sedang', 8, 'Rata-rata dari 5, 8, 9, 12, 6 adalah...', null,
    ['8', '9', '7', '8,5', '10'],
    1, 'Jumlah = 40, banyak data = 5 → rata-rata = 8.'),
  q('matematika', 'sulit', 9, 'Uang Rp1.000.000 ditabung dengan bunga tunggal 6% per tahun. Setelah 2 tahun jumlah uangnya menjadi...', null,
    ['Rp1.120.000', 'Rp1.060.000', 'Rp1.200.000', 'Rp1.180.000', 'Rp1.100.000'],
    1, 'Bunga = 6% × 2 × 1.000.000 = 120.000 → total = 1.120.000.'),
  q('matematika', 'sulit', 10, 'Andi dapat menyelesaikan pekerjaan dalam 6 hari, Budi dalam 12 hari. Jika dikerjakan bersama-sama, pekerjaan selesai dalam...', null,
    ['4 hari', '5 hari', '3 hari', '6 hari', '2 hari'],
    1, 'Kecepatan bersama = 1/6 + 1/12 = 2/12 + 1/12 = 3/12 = 1/4 → selesai dalam 4 hari.'),
  q('matematika', 'sulit', 11, 'Harga awal Rp1.200.000, diskon 25%, lalu mendapat tambahan potongan 10% dari harga setelah diskon. Uang yang dibayar adalah...', null,
    ['Rp810.000', 'Rp780.000', 'Rp900.000', 'Rp840.000', 'Rp820.000'],
    1, 'Setelah diskon 25%: 1.200.000 × 0,75 = 900.000. Potongan 10% lagi: 900.000 × 0,9 = 810.000.'),
  q('matematika', 'sulit', 12, 'Perbandingan umur Ayah : Anak = 5 : 2. Selisih umur mereka 18 tahun. Umur Ayah adalah...', null,
    ['30 tahun', '12 tahun', '25 tahun', '36 tahun', '28 tahun'],
    1, 'Selisih bagian = 3 → 1 bagian = 18/3 = 6. Umur Ayah = 5 × 6 = 30 tahun.'),

  // ============ TES KEPRIBADIAN ============
  q('kepribadian', 'sedang', 1, 'Tim Anda menghadapi tenggat pekerjaan yang sangat ketat. Sikap Anda yang paling tepat adalah...', null,
    ['Membagi tugas secara jelas sesuai kemampuan anggota', 'Mengerjakan semuanya sendiri agar cepat', 'Menunggu instruksi pimpinan tanpa inisiatif', 'Mengeluh dan menyalahkan anggota lain', 'Mengabaikan tenggat karena terburu-buru'],
    1, 'Kerja tim yang baik ditandai pembagian tugas dan koordinasi. Menumpuk pekerjaan sendiri berisiko kualitas menurun.'),
  q('kepribadian', 'sedang', 2, 'Saat menerima kritik atas hasil kerja Anda, reaksi yang paling baik adalah...', null,
    ['Menerima dengan terbuka dan memperbaiki diri', 'Membela diri habis-habisan', 'Diam dan tersinggung', 'Menyalahkan kondisi', 'Menghindar dari penilaian'],
    1, 'Kritik membangun diterima secara terbuka untuk perbaikan — tanda kedewasaan dan mau belajar.'),
  q('kepribadian', 'sedang', 3, 'Seorang rekan kerja mengalami kesulitan menyelesaikan tugasnya. Anda akan...', null,
    ['Menawarkan bantuan dan berbagi cara', 'Membiarkan karena itu tugasnya', 'Mengerjakan semua tugasnya', 'Melaporkan ke atasan tanpa berdiskusi', 'Menertawakan kesulitannya'],
    1, 'Saling membantu tanpa merampas tanggung jawab rekan mencerminkan sikap kolaboratif.'),
  q('kepribadian', 'sedang', 4, 'Anda mendapat tugas di luar deskripsi pekerjaan Anda. Tindakan terbaik adalah...', null,
    ['Mempelajarinya dan mengerjakannya dengan baik', 'Menolak karena bukan tugas Anda', 'Mengerjakan asal-asalan', 'Meminta orang lain mengerjakan', 'Mengeluh kepada semua orang'],
    1, 'Fleksibel dan mau belajar hal baru adalah nilai plus di dunia kerja.'),
  q('kepribadian', 'sedang', 5, 'Prioritas Anda saat bekerja adalah...', null,
    ['Hasil yang berkualitas dan selesai tepat waktu', 'Selesai cepat walau berantakan', 'Mendapat pujian atasan', 'Menghindari kesalahan apa pun', 'Mengikuti kebiasaan lama'],
    1, 'Keseimbangan kualitas dan ketepatan waktu menunjukkan profesionalisme dan tanggung jawab.'),
  q('kepribadian', 'sedang', 6, 'Terjadi perbedaan pendapat dengan rekan dalam rapat. Sikap Anda adalah...', null,
    ['Mendengarkan, lalu mencari solusi terbaik bersama', 'Memaksa pendapat Anda menang', 'Diam tanpa menyampaikan pendapat', 'Meninggalkan rapat', 'Membuat suasana memanas'],
    1, 'Musyawarah yang sehat dan saling menghargai pendapat adalah ciri komunikasi yang baik.'),

  // ============ TAMBAHAN TES VERBAL (13-20) ============
  q('verbal', 'mudah', 13, 'Sinonim kata "hebat" adalah...', null,
    ['luar biasa', 'biasa saja', 'buruk', 'kecil', 'lemah'],
    1, 'Hebat = luar biasa.'),
  q('verbal', 'mudah', 14, 'Antonim dari kata "rajin" adalah...', null,
    ['malas', 'ulet', 'giat', 'tekun', 'semangat'],
    1, 'Lawan kata rajin adalah malas.'),
  q('verbal', 'mudah', 15, 'Lengkapilah analogi: "Pilot : Pesawat = Nahkoda : ..."', null,
    ['Kapal', 'Bandara', 'Pelabuhan', 'Stasiun', 'Garasi'],
    1, 'Pilot mengemudikan pesawat; nahkoda mengemudikan kapal.'),
  q('verbal', 'sedang', 16, 'Sinonim kata "ambisius" adalah...', null,
    ['penuh ambisi', 'malas', 'putus asa', 'ragu', 'sabar'],
    1, 'Ambisius = penuh ambisi / berhasrat besar.'),
  q('verbal', 'sedang', 17, 'Antonim kata "konsisten" adalah...', null,
    ['berubah-ubah', 'tetap', 'stabil', 'ajeg', 'konstan'],
    1, 'Konsisten = tetap/ajeg; lawannya berubah-ubah.'),
  q('verbal', 'sedang', 18, 'Lengkapilah analogi: "Sapu : Lantai = Kuas : ..."', null,
    ['Dinding', 'Atap', 'Pintu', 'Jendela', 'Lantai'],
    1, 'Sapu untuk membersihkan lantai; kuas untuk mengecat dinding.'),
  q('verbal', 'sulit', 19, 'Antonim kata "pragmatis" adalah...', null,
    ['idealis', 'praktis', 'realistis', 'logis', 'efisien'],
    1, 'Pragmatis = mengutamakan hasil praktis; lawannya idealis (mengutamakan prinsip/cita-cita).'),
  q('verbal', 'sulit', 20, 'Lengkapilah analogi: "Sel : Jaringan = Atom : ..."', null,
    ['Molekul', 'Proton', 'Elektron', 'Quark', 'Neutron'],
    1, 'Kumpulan sel membentuk jaringan; kumpulan atom membentuk molekul.'),

  // ============ TAMBAHAN TES NUMERIK (13-20) ============
  q('numerik', 'mudah', 13, 'Hitung: 10 + 15 - 5 = ...', null,
    ['20', '25', '15', '30', '10'],
    1, '10 + 15 = 25; 25 - 5 = 20.'),
  q('numerik', 'mudah', 14, 'Lanjutkan deret: 5, 10, 15, 20, ...', null,
    ['25', '30', '22', '24', '18'],
    1, 'Pola tambah 5 setiap langkah → 20 + 5 = 25.'),
  q('numerik', 'mudah', 15, 'Hitung: 1/3 + 1/6 = ...', null,
    ['1/2', '2/9', '1/4', '1/3', '2/6'],
    1, 'Samakan penyebut: 2/6 + 1/6 = 3/6 = 1/2.'),
  q('numerik', 'sedang', 16, 'Lanjutkan deret: 1, 4, 9, 16, ...', null,
    ['25', '20', '36', '24', '30'],
    1, 'Pola bilangan kuadrat: 1², 2², 3², 4², 5² → 25.'),
  q('numerik', 'sedang', 17, 'Berapakah 30% dari 150?', null,
    ['45', '40', '50', '60', '30'],
    1, '30% × 150 = 45.'),
  q('numerik', 'sedang', 18, 'Jumlah bilangan genap 2 + 4 + 6 + ... + 20 adalah...', null,
    ['110', '100', '120', '130', '90'],
    1, 'Ada 10 bilangan. Jumlah = 10/2 × (2+20) = 5 ×22 = 110.'),
  q('numerik', 'sulit', 19, 'Lanjutkan deret: 1, 2, 4, 7, 11, 16, ...', null,
    ['22', '20', '23', '21', '24'],
    1, 'Pola: +1, +2, +3, +4, +5, +6 → 16 + 6 = 22.'),
  q('numerik', 'sulit', 20, 'Usia ayah tiga kali usia anak. Jumlah usia mereka 56 tahun. Usia ayah adalah...', null,
    ['42', '40', '36', '44', '48'],
    1, 'Ayah + anak = 56; Ayah = 3 × anak → 4 × anak = 56 → anak = 14; ayah = 42.'),

  // ============ TAMBAHAN TES LOGIKA (13-20) ============
  q('logika', 'mudah', 13, 'Semua dokter memakai stetoskop. Rina adalah dokter. Kesimpulan yang benar adalah...', null,
    ['Rina memakai stetoskop', 'Rina tidak memakai stetoskop', 'Semua pemakai stetoskop adalah dokter', 'Rina bukan dokter', 'Tidak dapat disimpulkan'],
    1, 'Silogisme: semua dokter → stetoskop; Rina dokter → Rina memakai stetoskop.'),
  q('logika', 'mudah', 14, 'Jika A = B dan B = C, maka...', null,
    ['A = C', 'A ≠ C', 'C > A', 'A > C', 'Tidak dapat disimpulkan'],
    1, 'Sifat transitif kesamaan.'),
  q('logika', 'mudah', 15, '"Jika rajin maka pintar." Ani pintar. Apakah Ani pasti rajin?', null,
    ['Belum tentu, bisa pintar tanpa rajin', 'Pasti rajin', 'Pasti tidak rajin', 'Tidak pintar', 'Ani bodoh'],
    1, 'Pintar bisa diperoleh dari banyak sebab, tidak hanya dari rajin (modus ponens tidak berlaku mundur).'),
  q('logika', 'sedang', 16, 'Semua A = B. Sebagian B = C. Kesimpulan yang sahih...', null,
    ['Sebagian A = C', 'Semua C = A', 'Tidak ada A = C', 'Semua B = A', 'C tidak ada hubungannya'],
    1, 'Karena sebagian B sekaligus A dan C, maka sebagian A dan C beririsan.'),
  q('logika', 'sedang', 17, 'Jika hujan maka jalan basah. Ternyata jalan tidak basah. Maka...', null,
    ['Tidak hujan', 'Pasti hujan', 'Hujan tanpa sebab', 'Basah bukan karena hujan', 'Tidak dapat disimpulkan'],
    1, 'Modus tollens: p → q, ¬q, maka ¬p. Tidak hujan.'),
  q('logika', 'sedang', 18, 'Tinggi lima orang: A > B, C > A, D > C, E > A. Siapakah yang paling tinggi?', null,
    ['D', 'C', 'E', 'A', 'B'],
    1, 'Rantai: B < A < C < D, dan E > A. Karena D > C > A, maka D paling tinggi.'),
  q('logika', 'sulit', 19, 'Semua X = Y. Tidak ada Y = Z. Kesimpulan yang benar...', null,
    ['Tidak ada X yang merupakan Z', 'Semua X = Z', 'Sebagian X = Z', 'Semua Z = X', 'Tidak dapat disimpulkan'],
    1, 'Karena X ⊂ Y dan Y tidak beririsan dengan Z, maka X juga tidak beririsan dengan Z.'),
  q('logika', 'sulit', 20, 'Empat tim A, B, C, D. A > B, B > C, C > D. Pernyataan yang PASTI benar...', null,
    ['A > D', 'D > A', 'B = D', 'A = B', 'C > A'],
    1, 'Dari A > B > C > D maka A > D (transitif).'),

  // ============ TAMBAHAN TES SPASIAL (13-20) ============
  q('spasial', 'mudah', 13, 'Sebuah kubus memiliki berapa sisi?', null,
    ['6', '4', '8', '12', '10'],
    1, 'Kubus memiliki 6 sisi yang berbentuk persegi.'),
  q('spasial', 'mudah', 14, 'Jika sebuah titik diputar 360 derajat pada porosnya, posisi akhirnya...', null,
    ['Kembali ke posisi awal', 'Bergerak ke kiri', 'Bergerak ke kanan', 'Bergerak ke bawah', 'Tidak dapat ditentukan'],
    1, 'Satu putaran penuh (360°) akan mengembalikan titik ke posisi semula.'),
  q('spasial', 'mudah', 15, 'Bangun datar yang memiliki tepat 3 sudut (segitiga) disebut...', null,
    ['Segitiga', 'Persegi', 'Lingkaran', 'Trapesium', 'Heksagon'],
    1, 'Bangun dengan 3 sudut adalah segitiga.'),
  q('spasial', 'sedang', 16, 'Pola gambar berulang: lingkaran, kotak, segitiga, lingkaran, kotak, segitiga, ... Bentuk ke-7 adalah...', null,
    ['Segitiga', 'Lingkaran', 'Kotak', 'Bintang', 'Tidak dapat ditentukan'],
    1, 'Pola periodik 3 bentuk; ke-7 = 7 mod 3 = 1 → bentuk pertama = segitiga (posisi 3 dalam 1 siklus: 1=lingkaran, 2=kotak, 3=segitiga; 7 = 2 siklus + 1 = posisi ke-1 dari siklus ke-3 = segitiga).'),
  q('spasial', 'sedang', 17, 'Huruf "A" jika dicerminkan terhadap garis vertikal (kiri-kanan), hasilnya...', null,
    ['Tetap huruf A', 'Huruf V', 'Huruf terbalik', 'Huruf H', 'Tidak berubah bentuk'],
    1, 'Huruf A memiliki sumbu simetri vertikal sehingga hasil cerminnya tetap A.'),
  q('spasial', 'sedang', 18, 'Sebuah persegi panjang dipotong diagonal dari sudut kiri-atas ke kanan-bawah, menghasilkan berapa segitiga?', null,
    ['2', '3', '4', '1', '5'],
    1, 'Satu diagonal membagi persegi panjang menjadi 2 segitiga.'),
  q('spasial', 'sulit', 19, 'Sebuah titik berpindah setiap kali satu langkah secara diagonal: (1,1) → (2,2) → (3,3). Posisi ke-4 adalah...', null,
    ['(4,4)', '(1,2)', '(4,1)', '(2,1)', '(1,4)'],
    1, 'Pola bergerak satu langkah diagonal ke kanan-bawah setiap kali; langkah ke-4 = (4,4).'),
  q('spasial', 'sulit', 20, 'Huruf "F" dicerminkan terhadap garis horizontal (atas-bawah). Bentuk hasilnya paling mirip dengan...', null,
    ['Huruf F terbalik (kaki di atas)', 'Huruf F biasa', 'Huruf E', 'Huruf T', 'Garis lurus'],
    1, 'Pencerminan horizontal membalik F: bagian atas (garis pendek) berpindah ke bawah.'),

  // ============ TAMBAHAN TES MATEMATIKA DASAR (13-20) ============
  q('matematika', 'mudah', 13, 'Hitung: 2/3 + 1/6 = ...', null,
    ['5/6', '3/9', '1/2', '2/3', '3/6'],
    1, 'Samakan penyebut: 4/6 + 1/6 = 5/6.'),
  q('matematika', 'mudah', 14, 'Berapakah 40% dari 250?', null,
    ['100', '80', '120', '150', '90'],
    1, '40% × 250 = 0,4 × 250 = 100.'),
  q('matematika', 'mudah', 15, 'Keliling persegi dengan panjang sisi 12 cm adalah...', null,
    ['48 cm', '24 cm', '144 cm', '36 cm', '60 cm'],
    1, 'Keliling = 4 × sisi = 4 × 12 = 48 cm.'),
  q('matematika', 'sedang', 16, 'Sebuah toko memberi diskon 20% untuk barang Rp150.000. Harga yang harus dibayar adalah...', null,
    ['Rp120.000', 'Rp100.000', 'Rp130.000', 'Rp125.000', 'Rp135.000'],
    1, 'Diskon = 20% × 150.000 = 30.000 → bayar 150.000 - 30.000 = 120.000.'),
  q('matematika', 'sedang', 17, 'Luas persegi panjang dengan panjang 15 m dan lebar 8 m adalah...', null,
    ['120 m²', '23 m²', '46 m²', '100 m²', '240 m²'],
    1, 'Luas = p × l = 15 × 8 = 120 m².'),
  q('matematika', 'sedang', 18, 'Rata-rata dari bilangan 4, 6, 8, 10, 12 adalah...', null,
    ['8', '7', '9', '10', '6'],
    1, 'Jumlah = 40; banyak data = 5 → rata-rata = 40/5 = 8.'),
  q('matematika', 'sulit', 19, 'Kereta berangkat pukul 07:00 dengan kecepatan 80 km/jam. Jika jarak tempuh 200 km, kereta tiba pukul...', null,
    ['09:30', '08:30', '09:00', '10:00', '10:30'],
    1, 'Waktu = jarak/kecepatan = 200/80 = 2,5 jam. 07:00 + 2,5 = 09:30.'),
  q('matematika', 'sulit', 20, 'Volume tabung dengan jari-jari 7 cm dan tinggi 10 cm adalah... (π = 22/7)', null,
    ['1.540 cm³', '1.320 cm³', '770 cm³', '220 cm³', '440 cm³'],
    1, 'V = π × r² × t = 22/7 × 49 × 10 = 1.540 cm³.'),

  // ============ TAMBAHAN TES KEPRIBADIAN (7-20) ============
  q('kepribadian', 'mudah', 1, 'Saat Anda terlambat datang ke rapat, sikap yang paling tepat adalah...', null,
    ['Meminta maaf dan menjelaskan alasan singkat', 'Diam saja supaya tidak ketahuan', 'Menyalahkan jalanan macet', 'Pergi begitu saja tanpa pamit', 'Menyalahkan rekan yang tidak mengingatkan'],
    1, 'Tanggung jawab pribadi ditunjukkan dengan mengakui kesalahan dan memberi penjelasan.'),
  q('kepribadian', 'mudah', 2, 'Aturan baru diterapkan di tempat kerja Anda. Sikap yang sebaiknya diambil...', null,
    ['Mempelajari dan menerapkannya dengan benar', 'Mengabaikannya karena tidak setuju', 'Menunggu orang lain melaksanakannya dulu', 'Menerapkan setengah-setengah', 'Mengeluh ke semua rekan'],
    1, 'Bersikap adaptif dan terbuka terhadap perubahan adalah kunci pengembangan diri.'),
  q('kepribadian', 'mudah', 3, 'Rekan kerja berbeda pendapat dengan Anda. Anda sebaiknya...', null,
    ['Mendengarkan dengan terbuka dan berdiskusi', 'Memaksakan pendapat sendiri', 'Mendiamkan tanpa bicara', 'Menghindarinya', 'Menyebarkan ke orang lain'],
    1, 'Menghargai perbedaan pendapat dan berdiskusi adalah ciri kedewasaan.'),
  q('kepribadian', 'mudah', 4, 'Anda menyelesaikan tugas lebih cepat dari jadwal. Yang sebaiknya Anda lakukan...', null,
    ['Melaporkan hasil dan menawarkan bantuan ke tim', 'Pulang lebih awal tanpa memberi tahu', 'Diam dan menunggu tugas berikutnya', 'Menghabiskan waktu untuk hal tidak penting', 'Pamer hasil ke rekan'],
    1, 'Inisiatif membantu tim menunjukkan sikap kolaboratif dan profesional.'),
  q('kepribadian', 'sedang', 7, 'Bos memuji hasil kerja Anda di depan tim. Reaksi Anda sebaiknya...', null,
    ['Berterima kasih dengan rendah hati dan tetap fokus kerja', 'Pamer dan menyombongkan diri', 'Meremehkan kontribusi tim', 'Langsung minta kenaikan gaji', 'Bangga dan berhenti bekerja keras'],
    1, 'Rendah hati setelah mendapat penghargaan mencerminkan karakter yang kuat.'),
  q('kepribadian', 'sedang', 8, 'Anda gagal mencapai target yang ditetapkan. Tindakan yang dewasa adalah...', null,
    ['Mengevaluasi penyebab dan menyusun strategi baru', 'Menyalahkan keadaan atau rekan', 'Menyembunyikan kegagalan', 'Berhenti berusaha', 'Mengeluh tanpa bertindak'],
    1, 'Kegagalan adalah guru terbaik jika direspons dengan evaluasi dan perbaikan.'),
  q('kepribadian', 'sedang', 9, 'Anda diminta presentasi mendadak. Anda sebaiknya...', null,
    ['Menarik napas, susun poin utama, lalu sampaikan', 'Menolak karena panik', 'Berbicara panjang lebar tanpa arah', 'Diam dan minta diganti orang lain', 'Mengeluh kepada atasan'],
    1, 'Kemampuan tetap tenang dan fokus pada hal penting adalah kompetensi profesional.'),
  q('kepribadian', 'sedang', 10, 'Rekan kerja memotong pembicaraan Anda. Tindakan Anda sebaiknya...', null,
    ['Menunggu dengan sabar, lalu menyampaikan kembali dengan sopan', 'Langsung membalas memotong', 'Diam selamanya', 'Marah dan meninggalkannya', 'Menyebarkan ke orang lain'],
    1, 'Sabar dan tetap profesional mencerminkan kontrol emosi yang baik.'),
  q('kepribadian', 'sedang', 11, 'Informasi sensitif beredar di tempat kerja. Anda sebaiknya...', null,
    ['Tidak ikut menyebarkan dan konsultasi ke atasan', 'Langsung share ke semua orang', 'Membaca dan menambah komentar', 'Mengabaikannya tanpa peduli', 'Menyimpan untuk kepentingan pribadi'],
    1, 'Menjaga kerahasiaan informasi sensitif adalah bentuk integritas.'),
  q('kepribadian', 'sedang', 12, 'Tugas yang diberikan tidak sesuai dengan passion Anda. Anda akan...', null,
    ['Mengerjakan secara profesional sebagai bagian tanggung jawab', 'Menolak mentah-mentah', 'Mengerjakan asal-asalan', 'Mendelegasikan tanpa izin', 'Membocorkan ke luar'],
    1, 'Profesionalisme ditunjukkan dengan mengerjakan tugas di luar passion secara bertanggung jawab.'),
  q('kepribadian', 'sulit', 13, 'Kepentingan tim dan kepentingan pribadi saling bertentangan. Anda akan...', null,
    ['Mengutamakan kepentingan tim dengan komunikasi terbuka', 'Langsung memilih kepentingan sendiri', 'Menghindari situasi', 'Diam tanpa keputusan', 'Mengadu ke atasan langsung'],
    1, 'Integritas seorang profesional tampak saat bersedia mendahulukan kepentingan tim dengan dialog.'),
  q('kepribadian', 'sulit', 14, 'Instruksi atasan bertentangan dengan keyakinan pribadi Anda. Anda sebaiknya...', null,
    ['Menyampaikan keberatan secara profesional sambil mencari solusi', 'Melanggar instruksi secara diam-diam', 'Langsung menolak tanpa diskusi', 'Mengundurkan diri mendadak', 'Mematuhi tanpa pertimbangan'],
    1, 'Komunikasi asertif dan mencari solusi tengah adalah pendekatan dewasa.'),
  q('kepribadian', 'sulit', 15, 'Keputusan Anda berdampak negatif bagi tim. Anda akan...', null,
    ['Mengakui, minta maaf, perbaiki, dan jadikan pelajaran', 'Menyalahkan anggota tim lain', 'Menyembunyikan kesalahan', 'Mengelak dan menyalahkan keadaan', 'Tidak mengambil tanggung jawab'],
    1, 'Akuntabilitas adalah ciri pemimpin sejati: mengakui, memperbaiki, dan belajar.'),
  q('kepribadian', 'sulit', 16, 'Rekan kerja yang kurang kompeten menghambat kinerja tim. Anda sebaiknya...', null,
    ['Membantu dengan sabar dan melapor jika perlu ke atasan', 'Mengerjakan tugasnya diam-diam', 'Membiarkan dia gagal sendiri', 'Mengeluh tanpa memberi solusi', 'Menggantinya langsung'],
    1, 'Membantu dengan sabar mencerminkan kepemimpinan; melapor ke atasan adalah jalur formal jika diperlukan.')
];

module.exports = { categories, questions };